DROP TABLE PRODUTO;
Create table PRODUTO(
    NOME        VARCHAR(50),
    QTD         INTEGER,
    ATUALIZADO  TIMESTAMP
);

INSERT INTO PRODUTO(nome, qtd, atualizado) VALUES('PRODUTO X', 10, CURRENT_TIMESTAMP);
INSERT INTO PRODUTO(nome, qtd, atualizado) VALUES('PRODUTO Y', 15, CURRENT_TIMESTAMP);